[2024-09-07T14:24:17.974+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.compare_data2threshold manual__2024-09-07T14:23:37.967877+00:00 [queued]>
[2024-09-07T14:24:18.067+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.compare_data2threshold manual__2024-09-07T14:23:37.967877+00:00 [queued]>
[2024-09-07T14:24:18.068+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:24:18.261+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): compare_data2threshold> on 2024-09-07 14:23:37.967877+00:00
[2024-09-07T14:24:18.326+0000] {standard_task_runner.py:60} INFO - Started process 3269 to run task
[2024-09-07T14:24:18.399+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'compare_data2threshold', 'manual__2024-09-07T14:23:37.967877+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpsdcius_h']
[2024-09-07T14:24:18.415+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask compare_data2threshold
[2024-09-07T14:24:18.642+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:24:19.043+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.compare_data2threshold manual__2024-09-07T14:23:37.967877+00:00 [running]> on host 74653e659746
[2024-09-07T14:24:20.140+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='compare_data2threshold' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:23:37.967877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:23:37.967877+00:00'
[2024-09-07T14:24:20.185+0000] {new_data_management.py:40} INFO - unit_threshold : 200
[2024-09-07T14:24:20.186+0000] {new_data_management.py:41} INFO - global_threshold : 2000
[2024-09-07T14:24:20.697+0000] {new_data_management.py:58} INFO - Total des counts : 1970
[2024-09-07T14:24:20.697+0000] {new_data_management.py:64} INFO - Le total 1970 ne d√©passe pas le seuil global 2000
[2024-09-07T14:24:20.700+0000] {new_data_management.py:69} INFO - Au moins une ligne est au-dessus de unit_threshold
[2024-09-07T14:24:20.701+0000] {new_data_management.py:74} INFO - Nous devons reentrainer le model avec les nouvelles data
[2024-09-07T14:24:20.824+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:24:20.938+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=compare_data2threshold, execution_date=20240907T142337, start_date=20240907T142417, end_date=20240907T142420
[2024-09-07T14:24:21.237+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:24:21.441+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
