[2024-09-07T14:36:54.623+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:36:01.319398+00:00 [queued]>
[2024-09-07T14:36:54.658+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:36:01.319398+00:00 [queued]>
[2024-09-07T14:36:54.659+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:36:54.713+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_newDataTrain_temp> on 2024-09-07 14:36:01.319398+00:00
[2024-09-07T14:36:54.747+0000] {standard_task_runner.py:60} INFO - Started process 3640 to run task
[2024-09-07T14:36:54.784+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'create_newDataTrain_temp', 'manual__2024-09-07T14:36:01.319398+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpkm6eg08h']
[2024-09-07T14:36:54.789+0000] {standard_task_runner.py:88} INFO - Job 113: Subtask create_newDataTrain_temp
[2024-09-07T14:36:54.841+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:36:55.055+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:36:01.319398+00:00 [running]> on host 74653e659746
[2024-09-07T14:36:55.520+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='create_newDataTrain_temp' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:36:01.319398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:36:01.319398+00:00'
[2024-09-07T14:36:55.606+0000] {logging_mixin.py:188} INFO - retrain: False
[2024-09-07T14:36:55.607+0000] {new_data_management.py:89} INFO - retrain value from task 3 : False
[2024-09-07T14:36:55.608+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:36:55.663+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=create_newDataTrain_temp, execution_date=20240907T143601, start_date=20240907T143654, end_date=20240907T143655
[2024-09-07T14:36:55.776+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:36:55.939+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
