[2024-08-14T05:29:08.050+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_new_data.create_new_data_task manual__2024-08-14T05:29:01.332793+00:00 [queued]>
[2024-08-14T05:29:08.068+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_new_data.create_new_data_task manual__2024-08-14T05:29:01.332793+00:00 [queued]>
[2024-08-14T05:29:08.068+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-14T05:29:08.091+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_new_data_task> on 2024-08-14 05:29:01.332793+00:00
[2024-08-14T05:29:08.101+0000] {standard_task_runner.py:60} INFO - Started process 264 to run task
[2024-08-14T05:29:08.108+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_new_data', 'create_new_data_task', 'manual__2024-08-14T05:29:01.332793+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/create_new_data.py', '--cfg-path', '/tmp/tmpobemxsdj']
[2024-08-14T05:29:08.110+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask create_new_data_task
[2024-08-14T05:29:08.133+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-14T05:29:08.193+0000] {task_command.py:423} INFO - Running <TaskInstance: create_new_data.create_new_data_task manual__2024-08-14T05:29:01.332793+00:00 [running]> on host 2a2e5a0edc88
[2024-08-14T05:29:08.450+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_new_data' AIRFLOW_CTX_TASK_ID='create_new_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T05:29:01.332793+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T05:29:01.332793+00:00'
[2024-08-14T05:29:08.454+0000] {create_new_data.py:36} INFO - sample_size : 234
[2024-08-14T05:29:09.492+0000] {create_new_data.py:45} INFO - df_train_new shape : (770, 5)
[2024-08-14T05:29:09.492+0000] {create_new_data.py:46} INFO - df_stock shape : (41688, 5)
[2024-08-14T05:29:11.262+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-14T05:29:11.364+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_new_data, task_id=create_new_data_task, execution_date=20240814T052901, start_date=20240814T052908, end_date=20240814T052911
[2024-08-14T05:29:11.529+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-14T05:29:11.575+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
