[2024-08-16T18:52:21.656+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.compare_data2threshold manual__2024-08-16T18:52:04.660682+00:00 [queued]>
[2024-08-16T18:52:21.684+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.compare_data2threshold manual__2024-08-16T18:52:04.660682+00:00 [queued]>
[2024-08-16T18:52:21.685+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T18:52:21.722+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): compare_data2threshold> on 2024-08-16 18:52:04.660682+00:00
[2024-08-16T18:52:21.734+0000] {standard_task_runner.py:60} INFO - Started process 2221 to run task
[2024-08-16T18:52:21.745+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'compare_data2threshold', 'manual__2024-08-16T18:52:04.660682+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpr7nnnf6u']
[2024-08-16T18:52:21.754+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask compare_data2threshold
[2024-08-16T18:52:21.802+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T18:52:21.893+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.compare_data2threshold manual__2024-08-16T18:52:04.660682+00:00 [running]> on host f23221e116fc
[2024-08-16T18:52:22.189+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='compare_data2threshold' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T18:52:04.660682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T18:52:04.660682+00:00'
[2024-08-16T18:52:22.192+0000] {new_data_management.py:40} INFO - unit_threshold : 200
[2024-08-16T18:52:22.193+0000] {new_data_management.py:41} INFO - global_threshold : 2000
[2024-08-16T18:52:22.374+0000] {new_data_management.py:58} INFO - Total des counts : 4112
[2024-08-16T18:52:22.376+0000] {new_data_management.py:62} INFO - Le total 4112 d√©passe le seuil global 2000
[2024-08-16T18:52:22.378+0000] {new_data_management.py:69} INFO - Au moins une ligne est au-dessus de unit_threshold
[2024-08-16T18:52:22.379+0000] {new_data_management.py:74} INFO - Nous devons reentrainer le model avec les nouvelles data
[2024-08-16T18:52:22.477+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T18:52:22.523+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=compare_data2threshold, execution_date=20240816T185204, start_date=20240816T185221, end_date=20240816T185222
[2024-08-16T18:52:22.600+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T18:52:22.675+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
