[2024-08-16T18:25:58.072+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bucket_push_test.upload_to_s3 manual__2024-08-16T18:25:51.033827+00:00 [queued]>
[2024-08-16T18:25:58.103+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bucket_push_test.upload_to_s3 manual__2024-08-16T18:25:51.033827+00:00 [queued]>
[2024-08-16T18:25:58.103+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T18:25:58.156+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-08-16 18:25:51.033827+00:00
[2024-08-16T18:25:58.167+0000] {standard_task_runner.py:60} INFO - Started process 1384 to run task
[2024-08-16T18:25:58.173+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'bucket_push_test', 'upload_to_s3', 'manual__2024-08-16T18:25:51.033827+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/bucket_push_test.py', '--cfg-path', '/tmp/tmpdgtwp24g']
[2024-08-16T18:25:58.175+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask upload_to_s3
[2024-08-16T18:25:58.244+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T18:25:58.387+0000] {task_command.py:423} INFO - Running <TaskInstance: bucket_push_test.upload_to_s3 manual__2024-08-16T18:25:51.033827+00:00 [running]> on host f23221e116fc
[2024-08-16T18:25:58.790+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bucket_push_test' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T18:25:51.033827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T18:25:51.033827+00:00'
[2024-08-16T18:25:58.825+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-08-16T18:25:58.826+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-08-16T18:26:01.176+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T18:26:01.233+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=bucket_push_test, task_id=upload_to_s3, execution_date=20240816T182551, start_date=20240816T182558, end_date=20240816T182601
[2024-08-16T18:26:01.342+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T18:26:01.446+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
