[2024-09-07T14:47:17.279+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:46:15.256634+00:00 [queued]>
[2024-09-07T14:47:17.383+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:46:15.256634+00:00 [queued]>
[2024-09-07T14:47:17.384+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:47:17.589+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_newDataTrain_temp> on 2024-09-07 14:46:15.256634+00:00
[2024-09-07T14:47:17.619+0000] {standard_task_runner.py:60} INFO - Started process 3989 to run task
[2024-09-07T14:47:17.630+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'create_newDataTrain_temp', 'manual__2024-09-07T14:46:15.256634+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpoj_tolyi']
[2024-09-07T14:47:17.636+0000] {standard_task_runner.py:88} INFO - Job 145: Subtask create_newDataTrain_temp
[2024-09-07T14:47:17.862+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:47:18.162+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:46:15.256634+00:00 [running]> on host 74653e659746
[2024-09-07T14:47:18.949+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='create_newDataTrain_temp' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:46:15.256634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:46:15.256634+00:00'
[2024-09-07T14:47:19.049+0000] {logging_mixin.py:188} INFO - retrain: True
[2024-09-07T14:47:19.050+0000] {new_data_management.py:89} INFO - retrain value from task 3 : True
[2024-09-07T14:47:36.422+0000] {new_data_management.py:110} INFO - X_train, y_train ready to be sent and retrain model
[2024-09-07T14:47:36.456+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:47:36.533+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=create_newDataTrain_temp, execution_date=20240907T144615, start_date=20240907T144717, end_date=20240907T144736
[2024-09-07T14:47:36.977+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:47:37.935+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
