[2024-08-16T18:48:27.299+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.compare_data2threshold manual__2024-08-16T18:48:15.640733+00:00 [queued]>
[2024-08-16T18:48:27.315+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.compare_data2threshold manual__2024-08-16T18:48:15.640733+00:00 [queued]>
[2024-08-16T18:48:27.315+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T18:48:27.341+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): compare_data2threshold> on 2024-08-16 18:48:15.640733+00:00
[2024-08-16T18:48:27.349+0000] {standard_task_runner.py:60} INFO - Started process 2088 to run task
[2024-08-16T18:48:27.354+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'compare_data2threshold', 'manual__2024-08-16T18:48:15.640733+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmp4fv4wg5j']
[2024-08-16T18:48:27.356+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask compare_data2threshold
[2024-08-16T18:48:27.378+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T18:48:27.427+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.compare_data2threshold manual__2024-08-16T18:48:15.640733+00:00 [running]> on host f23221e116fc
[2024-08-16T18:48:27.579+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='compare_data2threshold' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T18:48:15.640733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T18:48:15.640733+00:00'
[2024-08-16T18:48:27.582+0000] {new_data_management.py:36} INFO - unit_threshold : 200
[2024-08-16T18:48:27.582+0000] {new_data_management.py:37} INFO - global_threshold : 2000
[2024-08-16T18:48:27.646+0000] {new_data_management.py:54} INFO - Total des counts : 3136
[2024-08-16T18:48:27.647+0000] {new_data_management.py:58} INFO - Le total 3136 d√©passe le seuil global 2000
[2024-08-16T18:48:27.649+0000] {new_data_management.py:65} INFO - Au moins une ligne est au-dessus de unit_threshold
[2024-08-16T18:48:27.649+0000] {new_data_management.py:70} INFO - Nous devons reentrainer le model avec les nouvelles data
[2024-08-16T18:48:27.669+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T18:48:27.682+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=compare_data2threshold, execution_date=20240816T184815, start_date=20240816T184827, end_date=20240816T184827
[2024-08-16T18:48:27.728+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T18:48:27.771+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
