[2024-08-14T05:30:55.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_new_data.create_new_data_task manual__2024-08-14T05:30:49.917877+00:00 [queued]>
[2024-08-14T05:30:55.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_new_data.create_new_data_task manual__2024-08-14T05:30:49.917877+00:00 [queued]>
[2024-08-14T05:30:55.277+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-14T05:30:55.322+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_new_data_task> on 2024-08-14 05:30:49.917877+00:00
[2024-08-14T05:30:55.336+0000] {standard_task_runner.py:60} INFO - Started process 322 to run task
[2024-08-14T05:30:55.356+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_new_data', 'create_new_data_task', 'manual__2024-08-14T05:30:49.917877+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/create_new_data.py', '--cfg-path', '/tmp/tmpyoonnejr']
[2024-08-14T05:30:55.390+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask create_new_data_task
[2024-08-14T05:30:55.502+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-14T05:30:55.710+0000] {task_command.py:423} INFO - Running <TaskInstance: create_new_data.create_new_data_task manual__2024-08-14T05:30:49.917877+00:00 [running]> on host 2a2e5a0edc88
[2024-08-14T05:30:56.011+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_new_data' AIRFLOW_CTX_TASK_ID='create_new_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T05:30:49.917877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T05:30:49.917877+00:00'
[2024-08-14T05:30:56.016+0000] {create_new_data.py:36} INFO - sample_size : 234
[2024-08-14T05:30:56.726+0000] {create_new_data.py:45} INFO - df_train_new shape : (1004, 5)
[2024-08-14T05:30:56.727+0000] {create_new_data.py:46} INFO - df_stock shape : (41454, 5)
[2024-08-14T05:30:58.798+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-14T05:30:58.852+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_new_data, task_id=create_new_data_task, execution_date=20240814T053049, start_date=20240814T053055, end_date=20240814T053058
[2024-08-14T05:30:59.193+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-14T05:30:59.363+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
