[2024-09-07T14:24:31.091+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:23:37.967877+00:00 [queued]>
[2024-09-07T14:24:31.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:23:37.967877+00:00 [queued]>
[2024-09-07T14:24:31.160+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:24:31.253+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_newDataTrain_temp> on 2024-09-07 14:23:37.967877+00:00
[2024-09-07T14:24:31.272+0000] {standard_task_runner.py:60} INFO - Started process 3272 to run task
[2024-09-07T14:24:31.329+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'create_newDataTrain_temp', 'manual__2024-09-07T14:23:37.967877+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpf4lmn5zn']
[2024-09-07T14:24:31.332+0000] {standard_task_runner.py:88} INFO - Job 103: Subtask create_newDataTrain_temp
[2024-09-07T14:24:31.458+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:24:31.695+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-09-07T14:23:37.967877+00:00 [running]> on host 74653e659746
[2024-09-07T14:24:32.459+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='create_newDataTrain_temp' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:23:37.967877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:23:37.967877+00:00'
[2024-09-07T14:24:32.649+0000] {logging_mixin.py:188} INFO - retrain: True
[2024-09-07T14:24:32.649+0000] {new_data_management.py:89} INFO - retrain value from task 3 : True
[2024-09-07T14:24:41.870+0000] {new_data_management.py:110} INFO - X_train, y_train ready to be sent and retrain model
[2024-09-07T14:24:41.898+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:24:41.963+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=create_newDataTrain_temp, execution_date=20240907T142337, start_date=20240907T142431, end_date=20240907T142441
[2024-09-07T14:24:42.135+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:24:42.250+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
