[2024-08-17T09:46:39.988+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-08-17T09:45:13.082705+00:00 [queued]>
[2024-08-17T09:46:40.094+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-08-17T09:45:13.082705+00:00 [queued]>
[2024-08-17T09:46:40.095+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-17T09:46:40.233+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_newDataTrain_temp> on 2024-08-17 09:45:13.082705+00:00
[2024-08-17T09:46:40.263+0000] {standard_task_runner.py:60} INFO - Started process 31673 to run task
[2024-08-17T09:46:40.312+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'create_newDataTrain_temp', 'manual__2024-08-17T09:45:13.082705+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmp9wuiaof9']
[2024-08-17T09:46:40.325+0000] {standard_task_runner.py:88} INFO - Job 49: Subtask create_newDataTrain_temp
[2024-08-17T09:46:40.446+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-17T09:46:40.811+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.create_newDataTrain_temp manual__2024-08-17T09:45:13.082705+00:00 [running]> on host f23221e116fc
[2024-08-17T09:46:41.869+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='create_newDataTrain_temp' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T09:45:13.082705+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T09:45:13.082705+00:00'
[2024-08-17T09:46:41.987+0000] {logging_mixin.py:188} INFO - retrain: False
[2024-08-17T09:46:42.001+0000] {new_data_management.py:89} INFO - retrain value from task 3 : False
[2024-08-17T09:46:42.003+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-17T09:46:42.221+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=create_newDataTrain_temp, execution_date=20240817T094513, start_date=20240817T094639, end_date=20240817T094642
[2024-08-17T09:46:42.460+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-17T09:46:42.875+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
