[2024-08-13T16:19:23.557+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_new_data.create_new_data_task manual__2024-08-13T16:19:16.405451+00:00 [queued]>
[2024-08-13T16:19:23.573+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_new_data.create_new_data_task manual__2024-08-13T16:19:16.405451+00:00 [queued]>
[2024-08-13T16:19:23.574+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-13T16:19:23.604+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_new_data_task> on 2024-08-13 16:19:16.405451+00:00
[2024-08-13T16:19:23.610+0000] {standard_task_runner.py:60} INFO - Started process 1057 to run task
[2024-08-13T16:19:23.616+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_new_data', 'create_new_data_task', 'manual__2024-08-13T16:19:16.405451+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_new_data.py', '--cfg-path', '/tmp/tmp2sjwca3l']
[2024-08-13T16:19:23.619+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask create_new_data_task
[2024-08-13T16:19:23.646+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-13T16:19:23.702+0000] {task_command.py:423} INFO - Running <TaskInstance: create_new_data.create_new_data_task manual__2024-08-13T16:19:16.405451+00:00 [running]> on host 3be304d8e560
[2024-08-13T16:19:24.196+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_new_data' AIRFLOW_CTX_TASK_ID='create_new_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T16:19:16.405451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T16:19:16.405451+00:00'
[2024-08-13T16:19:24.199+0000] {create_new_data.py:36} INFO - sample_size : 302
[2024-08-13T16:19:25.686+0000] {create_new_data.py:45} INFO - df_train_new shape : (302, 5)
[2024-08-13T16:19:25.695+0000] {create_new_data.py:46} INFO - df_stock shape : (42156, 5)
[2024-08-13T16:19:28.868+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-13T16:19:28.910+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_new_data, task_id=create_new_data_task, execution_date=20240813T161916, start_date=20240813T161923, end_date=20240813T161928
[2024-08-13T16:19:28.997+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-13T16:19:29.054+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
